version: "~> 1.0"

language: java
os: linux
dist: bionic

env:
  - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}

before_install:
  - sudo apt update
  - sudo apt-get -y install --upgrade openjdk-8-jdk java-common
  - |
    if [ ! -f "$HOME/android_sdk/tools/sdkmanager" ]; then
       wget https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip -O /tmp/android-sdk.zip
       mkdir -p $HOME/android_sdk
       unzip -o /tmp/android-sdk.zip -d $HOME/android_sdk
    fi
  - yes | $HOME/android_sdk/tools/bin/sdkmanager --sdk_root=$HOME/android_sdk --licenses
  - $HOME/android_sdk/tools/bin/sdkmanager --sdk_root=$HOME/android_sdk --install "platforms;android-29"
  - $HOME/android_sdk/tools/bin/sdkmanager --sdk_root=$HOME/android_sdk --install "build-tools;29.0.3"
  - echo "sdk.dir=$HOME/android_sdk" >> local.properties

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/android_sdk
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - echo $PWD
  - echo ${gh_ci_key} | base64 --decode > github_deploy_key
  - chmod 600 github_deploy_key
  - md5sum github_deploy_key
  - git config user.name ziti-ci
  - git config user.email ziti-ci@netfoundry.io
  - git config core.sshCommand "ssh -i github_deploy_key"
  - git remote set-url origin git@github.com:${TRAVIS_REPO_SLUG}

stages:
  - name: test and build

  - name: tag and publish
    if: branch = master and type != pull_request

jobs:
  include:

    - stage: test and build
      script:
        - export PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:${PATH}
        - echo $PATH
        - which javac
        - javac -version
        - ./gradlew build
        - ./gradlew :ziti:check
        - ./gradlew :ziti-android:check

    - stage: tag and publish
      script:
        - ./gradlew :tagIfNeeded
        - ./gradlew build assemble
        - ./gradlew bintrayUpload -Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_API_KEY}
        - git push --tags --verbose
