[versions]
kotlin = "2.1.0"
openziti = "0.30.3"
springboot = "3.3.3"
clikt = "2.8.0"
slf4j = "2.0.5"

[libraries]
clikt = { module = "com.github.ajalt:clikt", version.ref = "clikt" }
okhttp3-okhttp = "com.squareup.okhttp3:okhttp:4.12.0"
netty-all = "io.netty:netty-all:4.1.113.Final"
httpclient5 = "org.apache.httpcomponents.client5:httpclient5:5.5.2"
httpcomponentscore5 = "org.apache.httpcomponents.core5:httpcore5:5.3.6"
httpcomponentscore5h2 = "org.apache.httpcomponents.core5:httpcore5-h2:5.3.6"
log4j = "org.apache.logging.log4j:log4j-core:2.17.1"
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1"
ziti = { module = "org.openziti:ziti", version.ref = "openziti" }
ziti-jdbc = { module = "org.openziti:ziti-jdbc", version.ref = "openziti" }
ziti-netty = { module = "org.openziti:ziti-netty", version.ref = "openziti" }
ziti-springboot = { module = "org.openziti:ziti-springboot", version.ref = "openziti" }
ziti-springboot-client = { module = "org.openziti:ziti-springboot-client", version.ref = "openziti" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
com-github-ben-manes-versions = "com.github.ben-manes.versions:0.51.0"
io-spring-dependency-management = "io.spring.dependency-management:1.1.6"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
org-springframework-boot = { id = "org.springframework.boot", version.ref = "springboot" }
